import audioAgoraEuEntendi from "../media/audio/AgoraEuEntendi.mp3";
import audioAiQueDelicia from "../media/audio/AiQueDelicia.mp3";
import audioAjudaSilvio from "../media/audio/AjudaSilvio.mp3";
import audioAquiTemCoragi from "../media/audio/AquiTemCoragi.mp3";
import audioArcoIro from "../media/audio/ArcoIro.mp3";
import audioBola from "../media/audio/Bola.mp3";
import audioCalcinha from "../media/audio/Calcinha.mp3";
import audioDesenhaNoQuadro from "../media/audio/DesenhaNoQuadro.mp3";
import audioDesseJeito from "../media/audio/DesseJeito.mp3";
import audioEAVerdade from "../media/audio/EAVerdade.mp3";
import audioEzatamentchy from "../media/audio/Ezatamentchy.mp3";
import audioFro from "../media/audio/Fro.mp3";
import audioGuda from "../media/audio/Guda.mp3";
import audioHojeNaoHojeSim from "../media/audio/HojeNaoHojeSim.mp3";
import audioIncrivel from "../media/audio/Incrivel.mp3";
import audioINHAAAAUUAAAAUU from "../media/audio/INHAAAAUUAAAAUU.mp3";
import audioMaisBurroQueParece from "../media/audio/MaisBurroQueParece.mp3";
import audioNaoConsigoGravar from "../media/audio/NaoConsigoGravar.mp3";
import audioNumSei from "../media/audio/NumSei.mp3";
import audioObjeto from "../media/audio/Objeto.mp3";
import audioQueDemais from "../media/audio/QueDemais.mp3";
import audioQueMerda from "../media/audio/QueMerda.mp3";
import audioRaciocinio from "../media/audio/Raciocinio.mp3";
import audioRAH from "../media/audio/RAH.mp3";
import audioSabiaNao from "../media/audio/SabiaNao.mp3";
import audioVaca from "../media/audio/Vaca.mp3";
import audioViolao from "../media/audio/Violao.mp3";
import audioVoceEBurroCara from "../media/audio/VoceEBurroCara.mp3";

export const agoraEuEntendi = audioAgoraEuEntendi;
export const aiQueDelicia = audioAiQueDelicia;
export const ajudaSilvio = audioAjudaSilvio;
export const aquiTemCoragi = audioAquiTemCoragi;
export const arcoIro = audioArcoIro;
export const bola = audioBola;
export const calcinha = audioCalcinha;
export const desenhaNoQuadro = audioDesenhaNoQuadro;
export const desseJeito = audioDesseJeito;
export const eAVerdade = audioEAVerdade;
export const ezatamentchy = audioEzatamentchy;
export const fro = audioFro;
export const guda = audioGuda;
export const hojeNaoHojeSim = audioHojeNaoHojeSim;
export const incrivel = audioIncrivel;
export const iNHAAAAUUAAAAUU = audioINHAAAAUUAAAAUU;
export const maisBurroQueParece = audioMaisBurroQueParece;
export const naoConsigoGravar = audioNaoConsigoGravar;
export const numSei = audioNumSei;
export const objeto = audioObjeto;
export const queDemais = audioQueDemais;
export const queMerda = audioQueMerda;
export const raciocinio = audioRaciocinio;
export const rAH = audioRAH;
export const sabiaNao = audioSabiaNao;
export const vaca = audioVaca;
export const violao = audioViolao;
export const voceEBurroCara = audioVoceEBurroCara;
