import imgAgoraEuEntendi from "../media/img/agoraEuEntendi.jpg";
import imgAjudaSilvio from "../media/img/ajudaSilvio.jpg";
import imgArcoIro from "../media/img/arcoIro.jpg";
import imgBola from "../media/img/bola.jpg";
import imgCalcinha from "../media/img/calcinha.jpg";
import imgCoragi from "../media/img/coragi.jpg";
import imgDemais from "../media/img/D+.jpg";
import imgDesseJeito from "../media/img/desseJeito.jpg";
import imgEzatamentchy from "../media/img/ezatamentchy.jpg";
import imgFro from "../media/img/fro.jpg";
import imgGuda from "../media/img/guda.jpg";
import imgHojeNao from "../media/img/hojeNao.jpg";
import imgIncrivel from "../media/img/incrivel.jpg";
import imgInhauau from "../media/img/inhauau.jpg";
import imgMaisBurroQueParece from "../media/img/MaisBurroQueParece.jpg";
import imgNaoConsigoGravar from "../media/img/naoConsigoGravar.jpg";
import imgNumSei from "../media/img/numSei.jpg";
import imgObjeto from "../media/img/objeto.jpg";
import imgQuadro from "../media/img/quadro.jpg";
import imgQueDelicia from "../media/img/queDelicia.jpg";
import imgQueMerda from "../media/img/queMerda.jpg";
import imgRaciocinio from "../media/img/raciocinio.jpg";
import imgRah from "../media/img/rah.jpg";
import imgRaqueta from "../media/img/raqueta.jpg";
import imgSabiaNao from "../media/img/sabiaNao.jpg";
import imgVaca from "../media/img/vaca.jpg";
import imgVerdade from "../media/img/verdade.jpg";
import imgViolao from "../media/img/violao.jpg";
import imgVoceEBurroCara from "../media/img/voceEBurroCara.jpg";

export const agoraEuEntendi = imgAgoraEuEntendi;
export const ajudaSilvio = imgAjudaSilvio;
export const arcoIro = imgArcoIro;
export const bola = imgBola;
export const calcinha = imgCalcinha;
export const coragi = imgCoragi;
export const demais = imgDemais;
export const desseJeito = imgDesseJeito;
export const ezatamentchy = imgEzatamentchy;
export const fro = imgFro;
export const guda = imgGuda;
export const hojeNao = imgHojeNao;
export const incrivel = imgIncrivel;
export const inhauau = imgInhauau;
export const maisBurroQueParece = imgMaisBurroQueParece;
export const naoConsigoGravar = imgNaoConsigoGravar;
export const numSei = imgNumSei;
export const objeto = imgObjeto;
export const quadro = imgQuadro;
export const queDelicia = imgQueDelicia;
export const queMerda = imgQueMerda;
export const raciocinio = imgRaciocinio;
export const rah = imgRah;
export const raqueta = imgRaqueta;
export const sabiaNao = imgSabiaNao;
export const vaca = imgVaca;
export const verdade = imgVerdade;
export const violao = imgViolao;
export const voceEBurroCara = imgVoceEBurroCara;
